name: ASports

on:
  schedule:
    - cron: "*/3 * * * *"
  workflow_dispatch:

jobs:
  ASports:
    runs-on: ubuntu-latest
    environment: Cricket

    steps:
      - name: Install ffmpeg
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Download remote bash file
        run: wget ${{secrets.A_SPORTS_URL }}

      - name: Install dos2unix
        run: sudo apt install dos2unix -y
                
      - name: Install libavcodec
        run: sudo apt install libavcodec-extra -y
        
      - name: Install inotifywait
        run: sudo apt install inotify-tools -y

      - name: Fix issue in downloaded file
        run: dos2unix asports.sh

      - name: Run the downloaded bash file
        run: bash asports.sh

      - name: Trigger new workflow
        if: always() || cancelled()
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.API_KEY }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/ASports.yml/dispatches \
            -d '{"ref":"main"}'
