name: Combine

on:
  workflow_dispatch:

jobs:
  Combine:
    runs-on: ubuntu-latest
    environment: Cricket

    steps:

      - name: Download remote bash file
        run: wget "${{ secrets.Main }}/ptv.sh"
        
      - name: Show Files
        run: ls
        
      - name: Show content
        run: nano ptv.sh
