name: PTVSports

on:
  workflow_dispatch:

jobs:
  PTVSports:
    runs-on: ubuntu-latest
    environment: Cricket
    # timeout-minutes: 1 # Set the maximum duration for the job

    steps:
      - name: Install ffmpeg
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Download remote bash file
        run: wget ${{secrets.PTV_SPORTS_URL }}

      - name: Install dos2unix
        run: sudo apt install dos2unix -y
        
      - name: Install libavcodec
        run: sudo apt install libavcodec-extra -y
        
      - name: Install inotifywait
        run: sudo apt install inotify-tools -y

      - name: Fix issue in downloaded file
        run: dos2unix ptv.sh

      - name: Run the downloaded bash file
        run: bash ptv.sh

      # - name: Trigger new workflow if canceled
      #   if: cancelled()
      #   run: |
      #     curl -X POST \
      #       -H "Authorization: token ${{ secrets.API_KEY }}" \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       https://api.github.com/repos/${{ github.repository }}/actions/workflows/PTVSports.yml/dispatches \
      #       -d '{"ref":"main"}'
