name: StarEng

on:
  workflow_dispatch:

jobs:
  StarEng:
    runs-on: ubuntu-latest
    environment: Cricket
    # timeout-minutes: 1 # Set the maximum duration for the job

    steps:
      - name: Install ffmpeg
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Download remote bash file
        run: wget ${{secrets.STAR_ENG_URL }}

      - name: Install dos2unix
        run: sudo apt install dos2unix -y
        
      - name: Install libavcodec
        run: sudo apt install libavcodec-extra -y
        
      - name: Install inotifywait
        run: sudo apt install inotify-tools -y
        
      - name: Fix issue in downloaded file
        run: dos2unix stareng.sh

      - name: Run the downloaded bash file
        run: bash stareng.sh

      - name: Trigger new workflow if canceled
        if: cancelled()
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.API_KEY }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/StarEng.yml/dispatches \
            -d '{"ref":"main"}'

  trigger_workflow:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Sleep for 5 hours and 58 minutes
        run: sleep $((5*3600 + 58*60))
      - name: Trigger new workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.API_KEY }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/StarEng.yml/dispatches \
            -d '{"ref":"main"}'
