name: VLC

on:
  workflow_dispatch:

jobs:
  VLC:
    runs-on: ubuntu-latest
    environment: Cricket

    steps:
      - name: Install ffmpeg and VLC
        run: |
          sudo apt update
          sudo apt install ffmpeg -y
          sudo apt-get install -y vlc

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a new user
        run: |
          sudo adduser --disabled-password --gecos "" newuser
          sudo usermod -aG sudo newuser
          echo "newuser ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/newuser

      - name: Test cvlc installation
        run: sudo su - newuser -c "cvlc --version"

      - name: Create Folder and set permissions
        run: |
          sudo mkdir -p /home/newuser/vlc
          sudo chmod 777 /home/newuser/vlc

      - name: Run basic cvlc stream (no video, no audio)
        run: |
          sudo -u newuser XDG_RUNTIME_DIR=/tmp HOME=/home/newuser /usr/bin/cvlc "http://starshare.org:8080/test5/5test/43444" \
          --no-dbus --intf dummy --no-globalhotkeys --no-video --no-audio

      - name: Run cvlc with transcoding
        run: |
          sudo -u newuser XDG_RUNTIME_DIR=/tmp HOME=/home/newuser /usr/bin/cvlc "http://starshare.org:8080/test5/5test/43444" \
          --no-dbus --intf dummy --no-globalhotkeys --no-video --no-audio \
          --sout '#transcode{vcodec=h264,vb=300,acodec=mp4a,ab=48,channels=2}:std{access=livehttp{seglen=10,delsegs=true,numsegs=5,index="/home/newuser/vlc/stream.m3u8",index-url="segment-########.ts"},mux=ts{use-key-frames},dst="/home/newuser/vlc/segment-########.ts"}' \
          --sout-all --sout-keep
