name: VLC

on:
  workflow_dispatch:

jobs:
  VLC:
    runs-on: ubuntu-latest
    environment: Cricket

    steps:
      - name: Install ffmpeg
        run: sudo apt update && sudo apt install ffmpeg -y
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a new user
        run: |
          sudo adduser --disabled-password --gecos "" newuser
          sudo usermod -aG sudo newuser
          echo "newuser ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/newuser

      - name: Install VLC
        run: sudo apt-get update && sudo apt-get install -y vlc

      - name: Run cvlc with the new user
        run: |
          sudo su - newuser -c "cvlc --version"

      - name: Run cvlc to play a media file
        run: |
          sudo -u newuser cvlc "http://starshare.org:8080/test5/5test/43444" \
          --no-dbus --intf dummy --http-reconnect --aout=file --no-globalhotkeys \
          --sout '#transcode{vcodec=h264,vb=300,acodec=mp4a,ab=48,channels=2}:std{access=livehttp{seglen=10,delsegs=true,numsegs=5,index="/tmp/stream.m3u8",index-url="segment-########.ts"},mux=ts{use-key-frames},dst="/tmp/segment-########.ts"}' \
          --sout-all --sout-keep


