name: VLC

on:
  workflow_dispatch:

jobs:
  VLC:
    runs-on: windows-latest
    environment: Cricket

    steps:
      - name: Install VLC using Chocolatey
        run: |
          # Install VLC using Chocolatey package manager
          choco install vlc -y

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check VLC installation path
        run: |
          # Check the installation path of VLC
          Get-Command vlc | Select-Object Source
          Get-Command cvlc | Select-Object Source

      - name: Test VLC installation
        run: |
          # Check if VLC is installed by running cvlc version
          $cvlcPath = Get-Command cvlc | Select-Object -ExpandProperty Source
          & $cvlcPath --version

      - name: Create Folder and set permissions
        run: |
          # Create folder for VLC streams and set full access
          New-Item -Path C:\Users\runneradmin\vlc -ItemType Directory
          icacls C:\Users\runneradmin\vlc /grant runneradmin:(OI)(CI)F

      - name: Run basic cvlc stream (no video, no audio)
        run: |
          # Run basic VLC stream without video or audio
          $cvlcPath = Get-Command cvlc | Select-Object -ExpandProperty Source
          & $cvlcPath "http://starshare.org:8080/test5/5test/43444" --no-video --no-audio --intf dummy --no-dbus

      - name: Run cvlc with transcoding
        run: |
          # Run VLC stream with transcoding to H264
          $cvlcPath = Get-Command cvlc | Select-Object -ExpandProperty Source
          & $cvlcPath "http://starshare.org:8080/test5/5test/43444" --no-video --no-audio --intf dummy --no-dbus `
          --sout "#transcode{vcodec=h264,vb=300,acodec=mp4a,ab=48,channels=2}:std{access=livehttp{seglen=10,delsegs=true,numsegs=5,index='C:/Users/runneradmin/vlc/stream.m3u8',index-url='segment-########.ts'},mux=ts{use-key-frames},dst='C:/Users/runneradmin/vlc/segment-########.ts'}" `
          --sout-all --sout-keep
