name: WillowCricket

on:
  workflow_dispatch:

jobs:
  WillowCricket:
    runs-on: ubuntu-latest
    environment: Cricket
    # timeout-minutes: 1 # Set the maximum duration for the job

    steps:
      - name: Install ffmpeg
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Download remote bash file
        run: wget ${{secrets.WILLOW_CRICKET_URL }}

      - name: Install dos2unix
        run: sudo apt install dos2unix -y
        
      - name: Install Git
        run: sudo apt install git -y
        
      - name: Install TorSocks
        run: sudo apt install torsocks -y
                
      - name: Install libavcodec
        run: sudo apt install libavcodec-extra -y
        
      - name: Install inotifywait
        run: sudo apt install inotify-tools -y

      - name: Fix issue in downloaded file
        run: sudo dos2unix willowcricket.sh
        
      - name: Permission to downloaded file
        run: sudo chmod +x willowcricket.sh
        
      - name: Permission to downloaded file
        run: sudo chmod 777 willowcricket.sh

      - name: Run the downloaded bash file
        run: sudo bash willowcricket.sh

  trigger_workflow:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - name: Sleep for 5 hours and 58 minutes
        run: sleep $((5*3600 + 58*60))
      - name: Trigger new workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.API_KEY }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/WillowCricket.yml/dispatches \
            -d '{"ref":"main"}'
